blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/IceTweak/hyperacc/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://pkg.go.dev/github.com/IceTweak/hyperacc
    about: Check the API documentation and examples
